### PR TITLE
Made demo use prisma instead of json file

### PR DESCRIPTION
**Pull request by md-y**

### CODE REVIEW

**Comment by md-y** [comment]
This makes the demo home page and /event page use the actual prisma database instead of a dummy json file. The pages are the same, but their routes and data sources are now different

**Review by md-y — COMMENTED** [review]
someone needs to review the changes to merge now btw

**Comment by md-y** [comment]
Also, fun fact:

You can use ```prisma studio``` or ```npx prisma studio``` to view the database from the browser and add events/other stuff manually

**Review by MStolen — APPROVED** [review]
@md-y, you're correct that reviews are needed. I'm still setting up auto assignment to Margi. Glad to see you were able to migrate the API to Prisma.

**Pull request merged**
